# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nu1zB4EfxnVMMkh2-wWNFDmSsuNkxSwD
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Read the CSV file
df = pd.read_csv("Startups.csv")

# Set the title for the Streamlit app
st.title('Global Startup Valuation Analysis')

# Convert valuation date to datetime
df['Valuation_date'] = pd.to_datetime(df['Valuation_date'], format='%B-%y')

# Create yearly aggregation
yearly_valuation = df.groupby(df['Valuation_date'].dt.year)['Valuation'].mean().reset_index()

# Display the line chart for valuation trend over years using Plotly
fig_yearly = px.line(yearly_valuation, x='Valuation_date', y='Valuation',
                     title='Average Startup Valuation Trend by Year',
                     labels={'Valuation_date': 'Year', 'Valuation': 'Average Valuation (Billion USD)'})
st.plotly_chart(fig_yearly)

# Industry Analysis
industry_valuation = df.groupby('Industry')['Valuation'].agg(['mean', 'count']).reset_index()
industry_valuation = industry_valuation.sort_values('mean', ascending=False)
industry_valuation = industry_valuation[industry_valuation['Industry'] != '']  # Remove empty industries

# Display industry breakdown
fig_industry = px.bar(industry_valuation.head(10),
                      x='Industry', y='mean',
                      title='Top 10 Industries by Average Valuation',
                      labels={'mean': 'Average Valuation (Billion USD)', 'Industry': 'Industry'})
st.plotly_chart(fig_industry)

# Geographical Analysis
country_valuation = df.groupby('Country')['Valuation'].mean().sort_values(ascending=False)
country_valuation = country_valuation.reset_index()

# Display country breakdown
fig_country = px.bar(country_valuation.head(10),
                     x='Country', y='Valuation',
                     title='Top 10 Countries by Average Startup Valuation',
                     labels={'Valuation': 'Average Valuation (Billion USD)', 'Country': 'Country'})
st.plotly_chart(fig_country)

# Key Insights
st.subheader('Key Insights')
total_companies = len(df)
avg_valuation = df['Valuation'].mean()
top_industry = industry_valuation.iloc[0]['Industry']
top_country = country_valuation.iloc[0]['Country']

st.write(f"""
- Total number of companies analyzed: {total_companies}
- Average company valuation: ${avg_valuation:.2f} billion
- Leading industry by valuation: {top_industry}
- Country with highest average valuations: {top_country}
""")

# Show raw data
if st.checkbox('Show Raw Data'):
    st.write(df)