# -*- coding: utf-8 -*-
"""app83.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rpOs0lonqSw7NBUfxERNI0lXE2ENWr-L
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import os


# Page configuration
st.set_page_config(page_title="Global Startup Valuation Analysis", layout="wide")
st.markdown("""
<div style="background: linear-gradient(120deg, #1E3D59, #17B794); padding: 2rem; border-radius: 10px;">
    <h2 style="color: white; text-align: center; font-size: 2.5rem; font-weight: bold; margin-bottom: 1.5rem;">
        Global Startup Valuation Analysis
    </h2>
</div>
""", unsafe_allow_html=True)

# Enhanced Custom CSS
st.markdown("""
<style>
    /* Section titles */
    .section-title {
        font-size: 2.2rem;
        font-weight: 600;
        color: #1E3D59;
        margin: 2rem 0 1rem 0;
        padding-bottom: 0.5rem;
        border-bottom: 3px solid #17B794;
    }

    /* Content text */
    .content-text {
        font-size: 1.1rem;
        line-height: 1.6;
        color: #2C3E50;
        background: #f8f9fa;
        padding: 1.5rem;
        border-radius: 8px;
        border-left: 5px solid #17B794;
    }

    /* Cards */
    .metric-card {
        background: white;
        padding: 1.5rem;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        text-align: center;
        transition: transform 0.3s ease;
    }

    .metric-card:hover {
        transform: translateY(-5px);
    }

    /* Metrics */
    .metric-value {
        font-size: 2rem;
        font-weight: 700;
        color: #17B794;
    }

    .metric-label {
        font-size: 1.1rem;
        color: #1E3D59;
    }

    /* Charts container */
    .chart-container {
        background: white;
        padding: 1.5rem;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        margin: 1.5rem 0;
    }
</style>
""", unsafe_allow_html=True)

# Read the CSV file (Ensure you have your data path correct)
df = pd.read_csv("Startups.csv")

# Introduction
st.markdown('<div class="content-text">The global startup ecosystem stands at a pivotal moment, characterized by dynamic valuations, emerging industries, and shifting geographical concentrations of innovation. This analysis provides a comprehensive overview of startup valuations across different dimensions, offering valuable insights for investors, entrepreneurs, and industry analysts. The data reveals trends in valuation growth, industry leadership, and geographical distribution that are critical to understanding the evolving market.</div>', unsafe_allow_html=True)

# Section: How Startups Change the Future of Work
st.markdown('<h2 class="section-title">How Startups Change the Future of Work</h2>', unsafe_allow_html=True)
col1, col2, col3 = st.columns(3)
with col1:
    st.markdown("""
    <div class="metric-card">
        <div class="metric-value">80%</div>
        <div class="metric-label">Business Model Innovation</div>
    </div>
    """, unsafe_allow_html=True)
with col2:
    st.markdown("""
    <div class="metric-card">
        <div class="metric-value">65%</div>
        <div class="metric-label">Digital Transformation</div>
    </div>
    """, unsafe_allow_html=True)
with col3:
    st.markdown("""
    <div class="metric-card">
        <div class="metric-value">92%</div>
        <div class="metric-label">Workforce Flexibility</div>
    </div>
    """, unsafe_allow_html=True)

# Section: Unprecedented Opportunities
st.markdown('<h2 class="section-header">Unprecedented Opportunities in the Startup Ecosystem</h2>', unsafe_allow_html=True)
st.markdown("""
<div class="insight-text">
The startup ecosystem presents unparalleled opportunities for value creation and innovation across various sectors. Advanced data analytics and machine learning capabilities enable startups to identify market gaps and develop solutions with unprecedented precision. These technological capabilities, combined with modern funding mechanisms, create an environment where innovative ideas can rapidly scale into global enterprises.
</div>
""", unsafe_allow_html=True)

# Bullet points for Modern Startups
st.markdown("""
<div class="insight-text">
Modern startups are leveraging:
<ul>
    <li>Advanced predictive analytics for market analysis</li>
    <li>Real-time data processing for decision making</li>
    <li>AI-driven customer insight generation</li>
    <li>Automated operational processes</li>
</ul>
</div>
""", unsafe_allow_html=True)

# Section: Business Readiness and Data Management
st.markdown('<h2 class="section-header">Business Readiness and Data Management</h2>', unsafe_allow_html=True)
st.markdown("""
<div class="insight-text">
Success in the startup ecosystem requires more than innovative ideas; it demands robust organizational infrastructure and data management capabilities. Key considerations include:
<ul>
    <li>Data Governance: Establishing frameworks for data collection, storage, and utilization</li>
    <li>Technical Infrastructure: Building scalable systems that can grow with the business</li>
    <li>Talent Management: Attracting and retaining skilled professionals who can drive innovation</li>
    <li>Risk Management: Implementing comprehensive risk assessment and mitigation strategies</li>
</ul>
The quality of data infrastructure and management systems often determines a startup's ability to scale and compete effectively in the global market. Success stories in the startup ecosystem consistently demonstrate the importance of building strong foundational systems while maintaining the agility to adapt to changing market conditions.
</div>
""", unsafe_allow_html=True)



# Section: Startup Success Use Cases
st.markdown('<h2 class="section-header">Startup Success Use Cases</h2>', unsafe_allow_html=True)

# Define the absolute paths for the images
image_paths = [
    ("/Users/solehahyunita/Downloads/streamlite/images/marketdisruption.jpg", "Market Disruption",
     "Startups leveraging innovative technologies to transform traditional markets and create new business models."),
    ("/Users/solehahyunita/Downloads/streamlite/images/scalingstrategies.jpg", "Scaling Strategies",
     "Successful approaches to rapid growth and market expansion in competitive environments."),
    ("/Users/solehahyunita/Downloads/streamlite/images/valuecreation.jpg", "Value Creation",
     "Methods for building and maintaining sustainable competitive advantages in global markets."),
]

col1, col2, col3 = st.columns(3)

for col, (image_path, title, description) in zip([col1, col2, col3], image_paths):
    absolute_path = os.path.abspath(image_path)
    with col:
        st.image(absolute_path, use_container_width=True, caption=title)  # Updated here
        st.markdown(f"<p style='color: #2C3E50; font-size: 1rem; line-height: 1.5;'>{description}</p>", unsafe_allow_html=True)

# Add custom CSS for the zoom effect
st.markdown("""
    <style>
        .zoom-img:hover {
            transform: scale(1.1); /* Slight zoom effect */
        }
    </style>
""", unsafe_allow_html=True)






# Visualizations Section
st.markdown('<h2 class="section-title">Startup Valuation Analysis</h2>', unsafe_allow_html=True)

# 1. Temporal Evolution of Valuations
# Convert date format and sort
df['Valuation_date'] = pd.to_datetime(df['Valuation_date'], format='%B-%y')
df_sorted = df.sort_values('Valuation_date')

# Insight for Temporal Evolution
st.markdown("""
<div class="content-text">
    <strong>Temporal Evolution of Startup Valuations:</strong>
    <p>The temporal evolution of startup valuations provides crucial insights into market trends over time.
    This visualization highlights fluctuations in valuations, allowing us to identify key growth periods and
    potential downturns in the startup ecosystem. Analyzing these trends helps stakeholders understand
    how external factors such as economic conditions and technological advancements impact startup funding.</p>
    <p>For instance, spikes in valuations may correspond with significant technological breakthroughs or favorable
    regulatory changes that encourage investment. Conversely, downturns may reflect economic uncertainty or market corrections.</p>
</div>
""", unsafe_allow_html=True)

# Create temporal evolution visualization
fig_timeline = px.line(
    df_sorted,
    x='Valuation_date',
    y='Valuation',
    title='Startup Valuations Over Time',
)
fig_timeline.update_layout(
    xaxis_title="Date",
    yaxis_title="Valuation (Billion USD)",
    template='plotly_white',
    height=500,
    hovermode='x unified'
)
st.plotly_chart(fig_timeline, use_container_width=True)

# 2. Industry Distribution
st.markdown("""
<div class="content-text">
    <strong>Industry Distribution of Startup Valuations:</strong>
    <p>Understanding the average valuations across different industries is critical for identifying sectors
    that are leading in innovation and investment. This bar chart illustrates the top 10 industries by
    average valuation, showcasing where significant investments are being made.</p>
    <p>For example, industries such as Fintech and Healthtech are seeing higher valuations due to increased
    demand for digital solutions and healthcare innovations, especially in the wake of the pandemic. This
    data provides investors with insights into which sectors may offer the best opportunities for growth.</p>
</div>
""", unsafe_allow_html=True)

# Calculate average valuation by industry and sort
industry_avg = df.groupby('Industry')['Valuation'].mean().sort_values(ascending=True)
top_10_industries = industry_avg.tail(10)

col1, col2 = st.columns(2)

with col1:
    fig_industry = px.bar(
        x=top_10_industries.values,
        y=top_10_industries.index,
        orientation='h',
        title='Top 10 Industries by Average Valuation',
    )
    fig_industry.update_layout(
        xaxis_title="Average Valuation (Billion USD)",
        yaxis_title="Industry",
        template='plotly_white',
        height=500,
        showlegend=False
    )
    st.plotly_chart(fig_industry, use_container_width=True)

with col2:
    # Define df_top_industries based on the top 10 industries
    df_top_industries = df[df['Industry'].isin(top_10_industries.index)]

    # Scatter plot of valuation vs time with industry color coding
    fig_scatter = px.scatter(
        df_top_industries,
        x='Valuation_date',
        y='Valuation',
        color='Industry',
        title='Valuation Distribution Over Time by Industry'
    )
    fig_scatter.update_layout(
        xaxis_title="Date",
        yaxis_title="Valuation (Billion USD)",
        template='plotly_white',
        height=500
    )
    st.plotly_chart(fig_scatter, use_container_width=True)

# 3. Geographical Distribution
st.markdown("""
<div class="content-text">
    <strong>Geographical Distribution of Startup Valuations:</strong>
    <p>The geographical distribution of valuations provides insights into the global landscape of startup investments.
    This map visualization illustrates total valuations by country, highlighting regions leading in startup activity
    and investment. Understanding these geographical trends is essential for investors looking to target their
    investments effectively.</p>
    <p>North America continues to dominate the startup ecosystem, but emerging markets in Asia and Europe are rapidly
    gaining ground. This shift indicates a diversification of opportunities, particularly in regions embracing
    digital transformation.</p>
</div>
""", unsafe_allow_html=True)

# Prepare data for the map
country_data = df.groupby('Country')['Valuation'].sum().reset_index()
country_data.columns = ['Country', 'Total Valuation']

# Create the map visualization
fig_map = px.choropleth(
    country_data,
    locations='Country',
    locationmode='country names',
    color='Total Valuation',
    hover_name='Country',
    color_continuous_scale=px.colors.sequential.Plasma,
    title='Total Startup Valuations by Country',
    labels={'Total Valuation': 'Total Valuation (Billion USD)'},
)

fig_map.update_geos(
    visible=False,
    showcoastlines=True,
    showcountries=True,
)

fig_map.update_layout(
    template='plotly_white',
    height=500,
)

st.plotly_chart(fig_map, use_container_width=True)



# Key Insights
st.markdown('<h2 class="section-title">Key Insights and Analysis</h2>', unsafe_allow_html=True)

# Add CSS for content styling (This can be defined just once)
st.markdown("""
    <style>
        .content-text {
            font-family: Arial, sans-serif; /* Set font family */
            color: #2C3E50; /* Text color */
            font-size: 1rem; /* Text size */
            line-height: 1.5; /* Line height */
        }
        .content-text ul {
            margin: 0; /* Remove default margin */
            padding-left: 20px; /* Indent list items */
        }
    </style>
""", unsafe_allow_html=True)

# Market Overview
st.markdown("""
<div class="content-text">
    <strong>Market Overview:</strong>
    <ul>
        <li>Total Market Capitalization: $1,955.21 billion</li>
        <li>Average Startup Valuation: $7.82 billion</li>
        <li>Growth Rate: 21.6% YoY</li>
    </ul>
</div>
""", unsafe_allow_html=True)

# Key Insights in Startup Valuations
st.markdown("""
<div class="content-text">
    <strong>Key Insights in Startup Valuations:</strong>
    <p> The analysis of startup valuations reveals significant trends and patterns that are essential for understanding
    the current market landscape. The total market capitalization reflects a robust ecosystem that is growing rapidly.
    With an average startup valuation of $7.82 billion, this indicates a strong appetite for investment in innovative
    sectors. </p>

    <p> The year-over-year growth rate of 21.6% signifies not just recovery from previous downturns but also an
    expanding interest from venture capitalists and institutional investors. This growth is particularly notable in
    technology-driven industries, which are attracting a majority of the capital. </p>

    <p> Furthermore, our findings suggest that certain industries, such as Fintech and Healthtech, are outpacing others
    in terms of valuation growth. For example, the Fintech sector has seen valuations skyrocketing due to the
    increasing digitization of financial services and the rise of decentralized finance solutions. </p>

    <p> Geographically, North America continues to dominate the startup ecosystem, accounting for a substantial
    share of total valuations. However, emerging markets in Asia and Europe are beginning to close the gap, with
    notable growth in regions like Southeast Asia, where digital transformation initiatives are gaining momentum. </p>

    <p> In summary, the startup valuation landscape is dynamic and influenced by a myriad of factors, including
    technological advancements, regulatory environments, and shifting consumer behaviors. Investors should remain
    vigilant and adaptable to navigate this evolving market effectively. </p>
</div>
""", unsafe_allow_html=True)


# Advanced Analytics
st.markdown('<h2 class="section-title">Advanced Analytics</h2>', unsafe_allow_html=True)
metrics_col1, metrics_col2, metrics_col3 = st.columns(3)
with metrics_col1:
    st.metric("Valuation Growth Rate", "21.6%", "5.4%")
with metrics_col2:
    st.metric("Industry Concentration", "8.8%", "-2.1%")
with metrics_col3:
    st.metric("Geographic Diversity", "53 countries", "4")

# Data Explorer
st.markdown('<h2 class="section-title">Data Explorer</h2>', unsafe_allow_html=True)
if st.checkbox('Show Raw Data'):
    st.dataframe(df)


# Footer Section
st.markdown("""
<div style="text-align: center; margin-top: 50px; padding: 20px; background: linear-gradient(120deg, #1E3D59, #17B794); border-top: 1px solid #17B794; border-radius: 10px;">
    <p style="font-size: 18px; font-weight: bold; color: white;">Don’t miss a beat. Get the latest AI news, right in your Inbox.</p>
    <a href="https://www.brandrev.ai" style="text-decoration: none; color: #f9f9f9; font-weight: bold;">Join our community</a>
    <br><br>
    <p style="font-size: 16px; color: #f9f9f9;">Leverage AI-powered solutions for sustainable revenue, efficient operations, and maximized client retention. Take the first step towards an AI-enabled future for your business with Brandrev.</p>
    <p style="margin-top: 15px; color: #f9f9f9;">Source data: <a href="https://www.kaggle.com/datasets/khaiid/startups-by-valuation" style="text-decoration: underline; color: #f9f9f9;">2022 Startups Dataset | Kaggle</a></p>
    <p style="margin-top: 15px; color: #f9f9f9;">&copy; Copyright 2024 Brandrev.AI. All rights reserved.</p>
</div>
""", unsafe_allow_html=True)

